---
format:
  html:
    embed-resources: true
book:
  title: "Fichamentos e referências"
  author: "Carlos de Moura"
  date: "06-01-2026"
lang: pt
bibliography: bib.bib
nocite: |
  @*
---

## Fichamentos

### @Haneuse2007 {.unnumbered}

We have individual-level (infants death) data and group-level (county) data.
* what does he calls ecological data? Is it the group-level data?
* "[After saying there is correlation between minority and teen preg. vs. mortality] However, estimating individual-level associations is not possible from the ecological data alone"
Why? What do they mean by "individual-level associations"?
"ecological data, consisting of the marginal numbers of deaths, minority babies, and teen mothers"
* 

Framework:

* $Y,X,Z$ são (resp.) as indicadoras de mortalizade, minoria e adolesc.
* $N_{yxzk} = \sum_{i \in I(k)} (Y_i = y)(X_i = x)(Z_i = z)$, toda a população do condado com essas características ou apenas a população de nascidos do condado?
* $M_{xzk} = \sum_{i \in I(k)} (X_i = x)(Z_i = z)$, toda a população do condado com essas características ou apenas a população de *nascidos* do condado? Acho que o 2º.
* $N_{yxzk} \sim \text{Binomial}(M_{xzk}, p_{xzk})$, em que

$$\operatorname{logit}(p_{xzk}) = \beta_0 + \beta_X x + \beta_Z z + \beta_{XZ} xz + V_k\ .$$
O efeito das covariáveis indicadores não depende do condado (não muda de condado para condado). Faz sentido pensar no contrário e manter o efeito aleatório?

* $V$ é assumido independente. Não é mais razoável assumir alguma estrutura de dependência?
* Why call $\beta$ the "baseline" odds? Ok it's clear now.
* Why "hybrid likelihood"?

Tentar fazer as contas da página 131

Aggregate Data Approach: Prentice, R. L. and Sheppard, L. (1995). Aggregate data studies of disease risk factors. Biometrika 82, 113-1

## Referências {.unnumbered}

::: {#refs}
:::
